apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: modelcontextprotocol-server-everything
  namespace: kagent
spec:
  deployment:
    args:
    - '@modelcontextprotocol/server-everything'
    cmd: npx
    image: node:24-alpine3.21
    port: 3000
  stdioTransport: {}
  transportType: stdio
