apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: github
  namespace: kagent
spec:
  description: "GitHub Copilot MCP Server"
  headersFrom:
  - name: Authorization
    value: Bearer github_pat_REPLACE_ME
  protocol: STREAMABLE_HTTP
  sseReadTimeout: 5m0s
  terminateOnClose: true
  timeout: 5s
  url: https://api.githubcopilot.com/mcp/
