apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: local-files-mcp-server
  namespace: kagent
spec:
  deployment:
    args:
    - '@modelcontextprotocol/server-filesystem'
    cmd: npx
    image: node:24-alpine3.21
    port: 3000
  stdioTransport: {}
  transportType: stdio
