apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  sync:
    kind: GitRepository
    url: "https://github.com/notawar/demo-cluster"
    ref: "refs/heads/main"
    path: "cluster/demo-cluster"
    pullSecret: "flux-system"