apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: jarvis-agent
  namespace: kagent
spec: 
  description: "J.A.R.V.I.S - Just A Rather Very Intelligent System - can admin and manage Kubernetes clusters, develop applications, and assist with various tasks using advanced AI capabilities."
  type: Declarative
  declarative:
    a2aConfig:
        skills:
        - description: The ability to analyze and diagnose Kubernetes Cluster issues.
          examples:
          - What is the status of my cluster?
          - How can I troubleshoot a failing pod?
          - What are the resource limits for my nodes?
          id: cluster-diagnostics
          name: Cluster Diagnostics
          tags:
          - cluster
          - diagnostics
        - description: The ability to manage and optimize Kubernetes resources.
          examples:
          - Scale my deployment X to 3 replicas.
          - Optimize resource requests for my pods.
          - Reserve more CPU for my nodes.
          id: resource-management
          name: Resource Management
          tags:
          - resource
          - management
        - description: The ability to audit and enhance Kubernetes security.
          examples:
          - Check for RBAC misconfigurations.
          - Audit my network policies.
          - Identify potential security vulnerabilities in my cluster.
          id: security-audit
          name: Security Audit
          tags:
          - security
          - audit
    modelConfig: ollama-gemma
    stream: true
    systemMessage: |
        You are Jarvis, an advanced AI assistant developed by KAgent Dev Team. Your purpose is to assist users with a variety of tasks using your advanced AI capabilities. You can help with managing Kubernetes clusters, developing applications, and providing intelligent solutions to complex problems. Always strive to provide accurate and helpful responses.
        
        # Instructions
        - Always respond in a concise and clear manner.
        - Ask for clarifcation when performing critical operations.
        - If you don't know how to answer the question DO NOT make things up
        respond with "Sorry, I don't know how to answer that" and ask the user to further clarify the question
        If you are unable to help, or something goes wrong, refer the user to https://kagent.dev for more information or support.

        # Response Format
        - ALWAYS use markdown formatting for all responses.
        - Your responses should summarize information in a short, clear manner.
        - When providing code snippets, use triple backticks to format the code blocks.

    tools:
      - mcpServer:
        kind: Service
        name: kagent-querydoc
        toolNames:
        - query_documentation
        type: McpServer
      - mcpServer:
          apiGroup: kagent.dev
          kind: RemoteMCPServer
          name: kagent-tool-server
          toolNames:
          - k8s_check_service_connectivity
          - k8s_patch_resource
          - k8s_remove_annotation
          - k8s_annotate_resource
          - k8s_remove_label
          - k8s_label_resource
          - k8s_create_resource
          - k8s_create_resource_from_url
          - k8s_get_events
          - k8s_get_available_api_resources
          - k8s_get_cluster_configuration
          - k8s_describe_resource
          - k8s_delete_resource
          - k8s_get_resource_yaml
          - k8s_execute_command
          - k8s_apply_manifest
          - k8s_get_resources
          - k8s_get_pod_logs
        type: McpServer