apiVersion: v1
kind: Pod
metadata:
  name: demo-agent
  namespace: kagent
  labels:
    app: kagent
    app.kubernetes.io/managed-by: kagent
    app.kubernetes.io/name: demo-agent
    app.kubernetes.io/part-of: kagent
    kagent: demo-agent
spec:
  serviceAccountName: demo-agent
  restartPolicy: Always

  containers:
    - name: kagent
      image: cr.kagent.dev/kagent-dev/kagent/app:0.7.13
      imagePullPolicy: IfNotPresent

      args:
        - --host
        - 0.0.0.0
        - --port
        - "8080"
        - --filepath
        - /config

      ports:
        - name: http
          containerPort: 8080
          protocol: TCP

      env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: kagent-openai
              key: OPENAI_API_KEY

        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://host.docker.internal:4317
        - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
          value: http://host.docker.internal:4317
        - name: OTEL_EXPORTER_OTLP_LOGS_INSECURE
          value: "true"
        - name: OTEL_EXPORTER_OTLP_LOGS_TIMEOUT
          value: "15"
        - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
          value: "true"
        - name: OTEL_EXPORTER_OTLP_TRACES_TIMEOUT
          value: "15"
        - name: OTEL_LOGGING_ENABLED
          value: "false"
        - name: OTEL_TRACING_ENABLED
          value: "false"
        - name: OTEL_TRACING_EXPORTER_OTLP_ENDPOINT
          value: http://host.docker.internal:4317

        - name: KAGENT_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KAGENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: KAGENT_URL
          value: http://kagent-controller.kagent:8083

      readinessProbe:
        httpGet:
          path: /health
          port: http
          scheme: HTTP
        initialDelaySeconds: 15
        periodSeconds: 15
        timeoutSeconds: 15
        successThreshold: 1
        failureThreshold: 3

      resources:
        requests:
          cpu: 100m
          memory: 384Mi
        limits:
          cpu: "2"
          memory: 1Gi

      volumeMounts:
        - name: config
          mountPath: /config
        - name: kagent-token
          mountPath: /var/run/secrets/tokens
          readOnly: true

  volumes:
    - name: config
      secret:
        secretName: demo-agent

    - name: kagent-token
      projected:
        sources:
          - serviceAccountToken:
              audience: kagent
              expirationSeconds: 3600
              path: kagent-token
