apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-model-loader
  namespace: ollama
spec:
  template:
    spec:
      containers:
      - name: model-loader
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          # Wait for Ollama service
          until curl -f http://ollama-svc.ollama.svc.cluster.local:11434/api/version; do
            echo "Waiting for Ollama..."
            sleep 5
          done
          
          # Pull essential models
          curl -X POST http://ollama-svc.ollama.svc.cluster.local:11434/api/pull \
            -H "Content-Type: application/json" \
            -d '{"name": "gemma3:1b"}'
          
      restartPolicy: Never
  backoffLimit: 3