---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kmcp
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: helm/kmcp
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: kmcp-repo
        namespace: kagent
