---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kmcp
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kmcp
      version: latest
      sourceRef:
        kind: HelmRepository
        name: kmcp-repo
        namespace: flux-system
