---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kmcp-repo
  namespace: kagent
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/kagent-dev/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kagent-repo
  namespace: kagent
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/kagent-dev/kagent/helm/